// Contact page translations
export const contactTranslations = {
  en: {
    // Contact page
    contactTitle: 'Contact Us',
    contactSubtitle: "We're here to help with any questions about the Sandviken Half-marathon",
    getInTouch: 'Get in Touch',
    contactDesc: "Have questions about the Sandviken Half-marathon? We're here to help!",
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    telephoneHours: 'Telephone 09:00-15:00',
    followUs: 'Follow Us',
    sendMessage: 'Send Us a Message',
    messageDesc: "Fill out the form below and we'll get back to you as soon as possible.",
    formName: 'Name',
    formEmail: 'Email',
    formSubject: 'Subject',
    formMessage: 'Message',
    sending: 'Sending...',
    successMessage: "Thank you for your message! We'll get back to you soon.",
    nameRequired: 'Name is required',
    nameMinLength: 'Name must be at least 2 characters',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email address',
    subjectRequired: 'Subject is required',
    subjectMinLength: 'Subject must be at least 3 characters',
    messageRequired: 'Message is required',
    messageMinLength: 'Message must be at least 10 characters',
    sendButton: 'Send Message'
  },
  sv: {
    // Contact page
    contactTitle: 'Kontakta Oss',
    contactSubtitle: 'Vi är här för att hjälpa till med alla frågor om Sandviken Halvmarathon',
    getInTouch: 'Kontakta Oss',
    contactDesc: 'Har du frågor om Sandviken Halvmarathon? Vi är här för att hjälpa till!',
    email: 'E-post',
    phone: 'Telefon',
    address: 'Adress',
    telephoneHours: 'Telefontider 09:00-15:00',
    followUs: 'Följ Oss',
    sendMessage: 'Skicka oss ett meddelande',
    messageDesc: 'Fyll i formuläret nedan så återkommer vi så snart som möjligt.',
    formName: 'Namn',
    formEmail: 'E-post',
    formSubject: 'Ämne',
    formMessage: 'Meddelande',
    sending: 'Skickar...',
    successMessage: 'Tack för ditt meddelande! Vi återkommer så snart som möjligt.',
    nameRequired: 'Namn krävs',
    nameMinLength: 'Namnet måste vara minst 2 tecken',
    emailRequired: 'E-post krävs',
    emailInvalid: 'Vänligen ange en giltig e-postadress',
    subjectRequired: 'Ämne krävs',
    subjectMinLength: 'Ämnet måste vara minst 3 tecken',
    messageRequired: 'Meddelande krävs',
    messageMinLength: 'Meddelandet måste vara minst 10 tecken',
    sendButton: 'Skicka Meddelande'
  }
};
