// Course page translations
export const courseTranslations = {
  en: {
    // Course page
    coursePageTitle: 'The Course',
    coursePageIntro: 'Experience a meticulously designed route that showcases the best of Sandviken',
    courseLength: 'Course Length',
    elevationGain: 'Elevation Gain',
    aidStations: 'Aid Stations',
    startFinish: 'Start/Finish',
    courseMap: 'Course Map',
    courseMapAlt: 'Sandviken Marathon Course Map',
    courseMapNote: 'View the interactive map to explore the full marathon route',
    courseMapInteractive: 'Click to view larger map',
    elevationProfile: 'Elevation Profile',
    courseDetailsTitle: 'Course Details',
    courseDescription: 'Our IAAF-certified marathon route takes you through the most scenic parts of Sandviken, offering a perfect balance of challenge and beauty.',
    courseHighlights: 'Course Highlights',
    scenicWaterfront: 'Scenic Waterfront',
    historicNeighborhoods: 'Historic Neighborhoods',
    forestViews: 'Forest Views',
    scenicRoads: 'Scenic Roads',
    waterStations: 'Water Stations',
    waterStationDetails: 'Offering water, sports drinks, and energy gels',
    medicalStations: 'Medical Stations',
    medicalStationDetails: 'Professional medical staff and first aid',
    raceDayInfo: 'Race Day Information',
    raceDayDetails: 'Everything you need to know for a successful race day experience',
    stadsparkenMapAlt: 'Map of Stadsparken (Start/Finish area)',
    startTime: 'Start Time',
    startTimeDetails: 'Marathon starts at 8:00 AM, Half Marathon at 8:15 AM, 10K at 8:30 AM',
    startLocation: 'Start Location',
    startLocationDetails: 'Stadsparken (City Park) in central Sandviken',
    supportAvailable: 'Support Available',
    supportDetails: 'Hydration, nutrition, and medical support throughout the course',
    moreInfo: 'More Information',
    contactOrganizers: 'Contact our race organizers for detailed information',
    riskManagementTitle: 'Risk Management & Safety',
    riskManagementDesc: 'Your safety is our top priority. Our comprehensive risk management plan includes emergency response teams stationed throughout the course, weather monitoring systems, and clear communication protocols. All participants receive detailed safety briefings, and our course is designed with multiple access points for emergency services.',
    staffingPlanTitle: 'Event Staff & Support',
    staffingPlanDesc: 'Our race is supported by over 200 trained volunteers and professional staff, including certified medical personnel, experienced race marshals, and dedicated aid station crews. Each kilometer of the course is monitored, and our command center maintains communication with all staff throughout the event.'
  },
  sv: {
    // Course page
    coursePageTitle: 'Banan',
    coursePageIntro: 'Upplev en noggrant utformad rutt som visar det bästa av Sandviken',
    courseLength: 'Banans Längd',
    elevationGain: 'Höjdskillnad',
    aidStations: 'Vätskestationer',
    startFinish: 'Start/Mål',
    courseMap: 'Bana Karta',
    courseMapAlt: 'Sandviken Marathon Bana Karta',
    courseMapNote: 'Visa den interaktiva kartan för att utforska hela maratonbanan',
    courseMapInteractive: 'Klicka för att visa större karta',
    elevationProfile: 'Höjdprofil',
    courseDetailsTitle: 'Bandetaljer',
    courseDescription: 'Vår IAAF-certifierade maratonbana tar dig genom de mest natursköna delarna av Sandviken och erbjuder en perfekt balans mellan utmaning och skönhet.',
    courseHighlights: 'Banans höjdpunkter',
    scenicWaterfront: 'Vacker Strandpromenad',
    historicNeighborhoods: 'Historiska Kvarter',
    forestViews: 'Skogsvyer',
    scenicRoads: 'Natursköna Vägar',
    waterStations: 'Vattenstationer',
    waterStationDetails: 'Erbjuder vatten, sportdrycker och energigel',
    medicalStations: 'Medicinska Stationer',
    medicalStationDetails: 'Professionell sjukvårdspersonal och första hjälpen',
    raceDayInfo: 'Information om Loppdag',
    raceDayDetails: 'Allt du behöver veta för en framgångsrik loppupplevelse',
    stadsparkenMapAlt: 'Karta över Stadsparken (Start/Målområde)',
    startTime: 'Starttid',
    startTimeDetails: 'Maraton startar kl 8:00, Halvmaraton kl 8:15, 10K kl 8:30',
    startLocation: 'Startplats',
    startLocationDetails: 'Stadsparken i centrala Sandviken',
    supportAvailable: 'Tillgängligt Stöd',
    supportDetails: 'Vätska, näring och medicinskt stöd längs hela banan',
    moreInfo: 'Mer Information',
    contactOrganizers: 'Kontakta våra lopparrangörer för detaljerad information',
    riskManagementTitle: 'Riskhantering & Säkerhet',
    riskManagementDesc: 'Din säkerhet är vår högsta prioritet. Vår omfattande riskhanteringsplan inkluderar akutteam stationerade längs banan, system för väderövervakning och tydliga kommunikationsprotokoll. Alla deltagare får detaljerade säkerhetsbriefingar, och vår bana är utformad med flera åtkomstpunkter för räddningstjänsten.',
    staffingPlanTitle: 'Evenemangspersonal & Support',
    staffingPlanDesc: 'Vårt lopp stöds av över 200 utbildade volontärer och professionell personal, inklusive certifierad sjukvårdspersonal, erfarna lopp-marskalkar och dedikerade vätskestation-team. Varje kilometer av banan övervakas, och vår kommandocentral upprätthåller kommunikation med all personal under hela evenemanget.'
  }
};
