// Course page translations
export const courseTranslations = {
  en: {
    // Course page
    coursePageTitle: 'The Course',
    coursePageIntro: 'Experience a meticulously designed route that showcases the best of Sandviken',
    courseHeading: 'Sandviken Half-marathon - Course Description',
    courseWelcomeText: 'Welcome to Sandviken Half-marathon, a race where every step is carried by nature\'s beauty, the city\'s pulse, and people\'s engagement. The start takes place in stadsparken Sandviken, with the course looping through Sandviken and extending southwards toward the coast and countryside before returning. Here runners, audience, and volunteers gather in a joint movement festival - with music, joy, and anticipation in the air.',
    courseLength: 'Course Length',
    elevationGain: 'Elevation Gain',
    aidStations: 'Aid Stations',
    startFinish: 'Start/Finish',
    courseMap: 'Course Map',
    courseMapAlt: 'Sandviken Half-marathon Course Map',
    courseMapNote: 'View the interactive map to explore the half-marathon route',
    courseMapInteractive: 'Click to view larger map',
    elevationProfile: 'Elevation Profile',
    courseDetailsTitle: 'Course Details',
    courseDescription: 'The Sandviken Half Marathon course is 21.1 km long with a total climb and descent of 74 m. The elevation profile is mostly flat with some gentle rolling hills, making it a relatively fast and manageable course. It starts in stadsparken Sandviken and loops through the town, extending southwards toward the coast and countryside before returning. The route passes through Barrsätra, Sätra, Stensätra, Säljan, and Örta neighborhoods, with parts running close to Lake Storsjön shoreline. The course combines both urban streets and more natural/forest areas, providing a scenic route that showcases Sandviken\'s unique blend of industrial heritage and natural beauty.',
    courseHighlights: 'Course Highlights',
    scenicWaterfront: 'Scenic Waterfront',
    historicNeighborhoods: 'Historic Neighborhoods',
    forestViews: 'Forest Views',
    scenicRoads: 'Scenic Roads',
    waterStations: 'Water Stations',
    waterStationDetails: 'Offering water, sports drinks, and energy gels',
    medicalStations: 'Medical Stations',
    medicalStationDetails: 'Professional medical staff and first aid',
    raceDayInfo: 'Race Day Information',
    raceDayDetails: 'Everything you need to know for a successful race day experience',
    stadsparkenMapAlt: 'Map of stadsparken Sandviken area (Start area)',
    startTime: 'Start Time',
    startTimeDetails: 'Half Marathon starts at 11:00 AM, Half Marathon at 11:15 AM, 10K at 11:30 AM',
    startLocation: 'Start Location',
    startLocationDetails: 'Near stadsparken Sandviken in Sandviken',
    supportAvailable: 'Support Available',
    supportDetails: 'Hydration, nutrition, and medical support throughout the course',
    moreInfo: 'More Information',
    contactOrganizers: 'Contact our race organizers for detailed information',
    riskManagementTitle: 'Risk Management & Safety',
    riskManagementDesc: 'Your safety is our top priority. Our comprehensive risk management plan includes emergency response teams stationed throughout the course, weather monitoring systems, and clear communication protocols. All participants receive detailed safety briefings, and our course is designed with multiple access points for emergency services.',
    staffingPlanTitle: 'Event Staff & Support',
    staffingPlanDesc: 'Our race is supported by over 200 trained volunteers and professional staff, including certified medical personnel, experienced race marshals, and dedicated aid station crews. Each kilometer of the course is monitored, and our command center maintains communication with all staff throughout the event.',

    // Detailed course description from file
    courseDescriptionEn: 'The Sandviken Half Marathon course is 21.1 km long with a total climb and descent of 74 m. The elevation profile is mostly flat with some gentle rolling hills, making it a relatively fast and manageable course. It starts near stadsparken Sandviken and loops through the town, extending southwards toward the coast and countryside before returning. The route passes through Barrsätra, Sätra, Stensätra, Säljan, and Örta neighborhoods, with parts running close to Lake Storsjön shoreline. The course combines both urban streets and more natural/forest areas, providing a scenic route that showcases Sandviken\'s unique blend of industrial heritage and natural beauty.',

    // Map reveal translations
    mapRevealTitle: 'Map Reveal Countdown',
    mapRevealMessage: 'The maps will be shown on 1/12-2025',
    mapRevealLabel: 'Time until maps are revealed'
  },
  sv: {
    // Course page
    coursePageTitle: 'Banan',
    coursePageIntro: 'Upplev en noggrant utformad rutt som visar det bästa av Sandviken',
    courseHeading: 'Sandviken Halvmarathon - Banbeskrivning',
    courseWelcomeText: 'Välkommen till Sandviken Halvmarathon, ett lopp där varje steg bärs av naturens skönhet, stadens puls och människors engagemang. Starten sker i stadsparken Sandviken, med banan som slingrar genom Sandviken och sträcker sig söderut mot sjön och landsbygden innan den återvänder. Här samlas löpare, publik och volontärer i en gemensam rörelsefest - med musik, glädje och förväntan i luften.',
    courseLength: 'Banans Längd',
    elevationGain: 'Höjdskillnad',
    aidStations: 'Vätskestationer',
    startFinish: 'Start/Mål',
    courseMap: 'Bana Karta',
    courseMapAlt: 'Sandviken Halvmarathon Bana Karta',
    courseMapNote: 'Visa den interaktiva kartan för att utforska hela halvmaratonbanan',
    courseMapInteractive: 'Klicka för att visa större karta',
    elevationProfile: 'Höjdprofil',
    courseDetailsTitle: 'Bandetaljer',
    courseDescription: 'Sandviken Halvmarathon-banan är 21,1 km lång med en total stigning på 74 m. Höjdprofilen är mestadels platt med några lätta kullar, vilket gör den relativt snabb och hanterbar. Den börjar i stadsparken Sandviken och slingrar genom staden, sträcker sig söderut mot sjön och landsbygden innan den återvänder. Rutten passerar genom Barrsätra, Sätra, Stensätra, Säljan och Örta stadsdelar, med delar som löper nära Storsjöns strandlinje. Banan kombinerar både urbana gator och mer naturliga/skogsområden, vilket ger en naturskön rutt som visar Sandvikens unika blandning av industriarv och naturlig skönhet.',
    courseHighlights: 'Banans höjdpunkter',
    scenicWaterfront: 'Vacker Strandpromenad',
    historicNeighborhoods: 'Historiska Kvarter',
    forestViews: 'Skogsvyer',
    scenicRoads: 'Natursköna Vägar',
    waterStations: 'Vattenstationer',
    waterStationDetails: 'Erbjuder vatten, sportdrycker och energigel',
    medicalStations: 'Medicinska Stationer',
    medicalStationDetails: 'Professionell sjukvårdspersonal och första hjälpen',
    raceDayInfo: 'Information om Loppdag',
    raceDayDetails: 'Allt du behöver veta för en framgångsrik loppupplevelse',
    stadsparkenMapAlt: 'Karta över stadsparken Sandviken (Startområde)',
    startTime: 'Starttid',
    startTimeDetails: 'Halvmaraton startar kl 11:00, Halvmaraton kl 11:15, 10K kl 11:30',
    startLocation: 'Startplats',
    startLocationDetails: 'I stadsparken Sandviken i Sandviken',
    supportAvailable: 'Tillgängligt Stöd',
    supportDetails: 'Vätska, näring och medicinskt stöd längs hela banan',
    moreInfo: 'Mer Information',
    contactOrganizers: 'Kontakta våra lopparrangörer för detaljerad information',
    riskManagementTitle: 'Riskhantering & Säkerhet',
    riskManagementDesc: 'Din säkerhet är vår högsta prioritet. Vår omfattande riskhanteringsplan inkluderar akutteam stationerade längs banan, system för väderövervakning och tydliga kommunikationsprotokoll. Alla deltagare får detaljerade säkerhetsbriefingar, och vår bana är utformad med flera åtkomstpunkter för räddningstjänsten.',
    staffingPlanTitle: 'Evenemangspersonal & Support',
    staffingPlanDesc: 'Vårt lopp stöds av över 200 utbildade volontärer och professionell personal, inklusive certifierad sjukvårdspersonal, erfarna lopp-marskalkar och dedikerade vätskestation-team. Varje kilometer av banan övervakas, och vår kommandocentral upprätthåller kommunikation med all personal under hela evenemanget.',

    // Detailed course description from file
    courseDescriptionSv: 'Sandviken Halvmarathon-banan är 21,1 km lång med stadsparken Sandviken total stigning på 74 m. Höjdprofilen är mestadels platt med några lätta kullar, vilket gör den relativt snabb och hanterbar. Den börjar i stadsparken Sandviken och slingrar genom staden, sträcker sig söderut mot sjön och landsbygden innan den återvänder. Rutten passerar genom Barrsätra, Sätra, Stensätra, Säljan och Örta stadsdelar, med delar som löper nära Storsjöns strandlinje. Banan kombinerar både urbana gator och mer naturliga/skogsområden, vilket ger en naturskön rutt som visar Sandvikens unika blandning av industriarv och naturlig skönhet.',

    // Map reveal translations
    mapRevealTitle: 'Kartavslutning Nedräkning',
    mapRevealMessage: 'Kartorna kommer att visas den 1/12-2025',
    mapRevealLabel: 'Tid tills kartorna avslöjas'
  }
};
