// Race day schedule translations
export const scheduleTranslations = {
  en: {
    // Race Day Schedule
    raceDaySchedule: 'Race Day Schedule',
    raceVillageOpens: '6:00 AM',
    raceVillageOpensText: 'Race village opens with registration, packet pickup, and vendor booths',
    warmupSession: '7:30 AM',
    warmupSessionText: 'Group warm-up session with professional trainer',
    marathonStart: '8:00 AM',
    marathonStartText: 'Marathon start from Sandviken Town Square',
    halfMarathonStart: '8:15 AM',
    halfMarathonStartText: 'Half marathon start',
    tenKStart: '8:30 AM',
    tenKStartText: '10K race start',
    awardsCeremony: '2:00 PM',
    awardsCeremonyText: 'Awards ceremony and closing celebration',
    eventDetailsLink: 'Event Details',

    // Event Details Tab
    eventDetailsSectionTitle: 'Event Details',
    eventSchedule: 'Event Schedule',
    preRaceDay: 'March 31, 2026',
    preRaceDayText: 'Pre-race expo and packet pickup (10:00 AM - 8:00 PM)',
    raceDayFullText: 'Race day with multiple start times (see race day schedule)',
    locationDetails: 'Location Details',
    startFinishArea: 'Start/Finish Area',
    startFinishAreaText: 'The start and finish are located in central Sandviken, at Stadsparken. Bessemerhallen provides changing rooms, restrooms, and the Expo (bib number pickup). Parking is available at Bessemerskolan, Parkbadet, Lidl, and Ica Maxi.',
    raceExpo: 'Race Expo',
    raceExpoText: 'Sandviken Convention Center, 123 Center Street',
    raceCategoriesDetails: 'Race Categories',
    marathonLabel: 'Marathon',
    halfMarathonLabel: 'Half Marathon',
    tenKRunLabel: '10K Run',
    importantInfo: 'Important Information',
    packetPickupInfo: 'All participants must pick up their race packets before race day',
    idRequired: 'Bring valid ID for packet pickup',
    noRaceDayRegistration: 'No race day registration will be available',
    timingChips: 'Timing chips must be returned after the race'
  },
  sv: {
    // Race Day Schedule
    raceDaySchedule: 'Tidsschema för loppdag',
    raceVillageOpens: '6:00',
    raceVillageOpensText: 'Tävlingsområdet öppnar med registrering, nummerlappsutdelning och utställare',
    warmupSession: '7:30',
    warmupSessionText: 'Gemensam uppvärmning med professionell tränare',
    marathonStart: '8:00',
    marathonStartText: 'Maratonstart från Sandvikens torg',
    halfMarathonStart: '8:15',
    halfMarathonStartText: 'Halvmaratonstart',
    tenKStart: '8:30',
    tenKStartText: '10K-loppstart',
    awardsCeremony: '14:00',
    awardsCeremonyText: 'Prisceremoni och avslutningsfirande',
    eventDetailsLink: 'Evenemangsdetaljer',

    // Event Details Tab
    eventDetailsSectionTitle: 'Evenemangsdetaljer',
    eventSchedule: 'Evenemangsschema',
    preRaceDay: '31 mars 2026',
    preRaceDayText: 'Expo före tävling och nummerlappsutdelning (10:00 - 20:00)',
    raceDayFullText: 'Tävlingsdag med flera starttider (se schema för tävlingsdagen)',
    locationDetails: 'Platsdetaljer',
    startFinishArea: 'Start/Målområde',
    startFinishAreaText: 'Start och mål är belägna i centrala Sandviken, vid Stadsparken. Bessemerhallen erbjuder omklädningsrum, toaletter och Expo (nummerlappsutdelning). Parkering finns vid Bessemerskolan, Parkbadet, Lidl och Ica Maxi.',
    raceExpo: 'Tävlingsexpo',
    raceExpoText: 'Sandvikens konferenscenter, Centergatan 123',
    raceCategoriesDetails: 'Tävlingskategorier',
    marathonLabel: 'Maraton',
    halfMarathonLabel: 'Halvmaraton',
    tenKRunLabel: '10K-lopp',
    importantInfo: 'Viktig information',
    packetPickupInfo: 'Alla deltagare måste hämta sina tävlingspaket före tävlingsdagen',
    idRequired: 'Ta med giltig legitimation för hämtning av tävlingspaket',
    noRaceDayRegistration: 'Ingen registrering kommer att finnas tillgänglig på tävlingsdagen',
    timingChips: 'Tidtagningschip måste återlämnas efter loppet'
  }
}; 